version: '3.8'

services:
  mysql-db:
    image: mysql:8.3
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: coworking_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - coworking-net

  coworking-app:
    build: .
    container_name: coworking-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    networks:
      - coworking-net

volumes:
  mysql_data:

networks:
  coworking-net:
